django-vue/backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from polls import views as polls_views
from cnn import views as cnn_views
from django.conf import settings
from django.conf.urls.static import static
# py ファイルを import することで html で py ファイルが利用可能になる
from polls.dash_apps.finished_apps import testplot, simpleexample, japanese_prefecture, avg_system_man

urlpatterns = [
    # polls ディレクトリと紐付け
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('cnn/', include('cnn.urls')),
    # 理由は分からないが、 django_plotly_dash のパスは必要
    # https://github.com/GibbsConsulting/django-plotly-dash/issues/117
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django-vue/backend/cnn/urls.py
from django.urls import path
from cnn import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = "cnn"
urlpatterns = [
    path('img_upload', views.img_upload, name='img_upload'),
    path('nueral_style', views.nueral_style, name='nueral_style'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-vue/backend/cnn/models.py
from django.db import models
from django import forms


def savePath(instance, filename):
    ext = filename.split('.')[-1]
    new_name = instance.title + "_saved"
    return f'files/{new_name}.{ext}'

# Create your models here.
class UploadImage(models.Model):
    title = models.CharField(max_length=100, default="nanashi")
    image = models.ImageField(upload_to=savePath)
    def __str__(self):
        return self.title, self.image

class Document(models.Model):
    # description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

django-vue/backend/cnn/forms.py
from django import forms
from .models import UploadImage
from .widgets import FileInputWithPreview
from .models import Document

# html の form で使用
class DateForm(forms.Form):
    start = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

class UploadForm(forms.ModelForm):
    class Meta:
        model = UploadImage
        fields = ['title', 'image']
        widgets = {
            'file': FileInputWithPreview,
            # 次のようにすると、プレビューエレメントがウィジェットに含まれない。つまりプレビューエレメントを自分で好きな場所にかける
            # 'file': FileInputWithPreview(include_preview=False)
        }


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = (
            # 'description',
            'document',
            )

django-vue/backend/cnn/views.py
from django.shortcuts import render, redirect
from .forms import UploadForm
from .models import UploadImage
import cv2
from django.conf import settings
import os
import logging
from .models import Document
from django.core.files.storage import FileSystemStorage
from .forms import DocumentForm
from .image_generator.def_nueral_style import NueralStyle

# Create your views here.
logger = logging.getLogger('development')
# logger.info('a-----------')

# def aaa_upload_img(request, num):
#     template_name = 'upload_img.html'
#     context = {
#         'title': '画像のアップロード',
#         'upload_form': UploadForm(),
#         'id': None,
#     }

#     if (request.method == 'POST'):
#         form = UploadForm(request.POST, request.FILES)
#         if form.is_valid():
            
#             upload_image = form.save()
#             print('b---------------')

#             context['id'] = upload_image.id
#             print(context)
#     return render(request, template_name, context)

def gray(url):
    img = cv2.imread(url)
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    output_path = "media/gallery"

    if not os.path.exists(output_path):
        os.mkdir(output_path)

    cv2.imwrite(output_path / "gray.jpg", img_gray)

# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
# def simple_upload(request):
#     if request.method == 'POST' and request.FILES['myfile']:
#         myfile = request.FILES['myfile']
#         fs = FileSystemStorage()
#         filename = fs.save(myfile.name, myfile)
#         uploaded_file_url = fs.url(filename)
#         return render(request, 'core/simple_upload.html', {
#             'uploaded_file_url': uploaded_file_url
#         })
#     return render(request, 'core/simple_upload.html')


def img_upload(request):
    template_name = 'upload_img.html'
    uploaded_file_url = ''
    gray_path = ''

    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            # ファイルの保存
            form.save()
            upload_img_file = request.FILES['document']
            fs = FileSystemStorage()
            filename = fs.save(upload_img_file.name, upload_img_file)
            uploaded_file_url = fs.url(filename)

            # views.py ではルートパスだと画像が読み込めないため、/を消す
            uploaded_file_url = uploaded_file_url[1:]

            # 拡張子の前で区切るため添字の取得
            target ='.'
            idx = uploaded_file_url.find(target)

            # 灰色の画像を保存するパスの作成と保存
            gray_path = uploaded_file_url[:idx]+'_gray'+uploaded_file_url[idx:]
            transform_gray(uploaded_file_url, gray_path)

            # html では / がついていないと画像が読み込めないため/をつけて渡す
            uploaded_file_url = '/' + uploaded_file_url
            gray_path = '/' + gray_path
    else:
        form = DocumentForm()
    
    data = {
        'form': form, 
        'uploaded_file_url': uploaded_file_url,
        'gray_path': gray_path,
    }

    return render(request, template_name, data)


def transform_gray(uploaded_file_url, gray_path):
    style_change_image = cv2.imread(uploaded_file_url)
    style_change_image = cv2.cvtColor(style_change_image, cv2.COLOR_BGR2GRAY)
    cv2.imwrite(gray_path, style_change_image)
    

def nueral_style(request):
    template_name = 'nueral_style_transform.html'
    form = DocumentForm(request.POST, request.FILES)
    transform_path = ''
    uploaded_file_url = ''

    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)

        if form.is_valid():
            print("valid")
            
             # ファイルの保存
            form.save()
            upload_img_file = request.FILES['document']
            fs = FileSystemStorage()
            filename = fs.save(upload_img_file.name, upload_img_file)
            uploaded_file_url = fs.url(filename)

            # views.py ではルートパスだと画像が読み込めないため、/を消す
            uploaded_file_url = uploaded_file_url[1:]

            # 拡張子の前で区切るため添字の取得
            target ='.'
            idx = uploaded_file_url.find(target)

            # 灰色の画像を保存するパスの作成と保存
            print("uploaded_file_url", uploaded_file_url)
            transform_path = uploaded_file_url[:idx]+'_transform'
            print("transform_path", transform_path)

            # ゴッホの画像の画像の指定
            STYLE_PATH = "media/cnn/1-style-gogh.jpg"

            nueral_style = NueralStyle(uploaded_file_url, STYLE_PATH, transform_path)
            nueral_style.stylize()
            # html に渡す時はrootにする
            uploaded_file_url = '/' + uploaded_file_url
            transform_path= transform_path + uploaded_file_url[idx+1:]
            transform_path = '/' + transform_path



    data = {
        'form': form, 
        'uploaded_file_url': uploaded_file_url,
        'transform_path': transform_path
    }

    return render(request, template_name, data)



    
# def img_upload(request):
#     print('---------')
#     print(request.FILES)
#     print('---------')

#     if request.method == 'POST' and request.FILES['myfile']:
#         myfile = request.FILES['myfile']
#         fs = FileSystemStorage()
#         filename = fs.save(myfile.name, myfile)
#         uploaded_file_url = fs.url(filename)
#         return render(request, 'upload_img.html', {
#             'uploaded_file_url': uploaded_file_url
#         })
#     return render(request, 'upload_img.html')

django-vue/backend/cnn/templates/nueral_style_transfer.html
{% extends "./base/_base.html" %} 
{% block content %}
<!-- UI 綺麗 -->
<!-- https://getbootstrap.jp/docs/5.0/forms/checks-radios/ -->

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>


  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    <p>File uploaded at: <a href="{{ gray_path }}">{{ uploaded_file_url }}</a></p>
    <img src="{{ uploaded_file_url }}" alt="">
    <img src="{{ gray_path }}" alt="">
  {% endif %}


<img src="static/sample.jpg">
{% endblock %}

django-vue/backend/cnn/templates/nueral_style_transform.html
{% extends "./base/_base.html" %} 
{% block content %}
<div class="container">
  <h3 class="space-bottom">画像をアップロードしてください</h3>
  <div class="d-flex flex-wrap mt-7">
    <form method="post" enctype="multipart/form-data">
      <div class="space-bottom">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      
      <div class="space-bottom">
        <button type="submit" class="btn-transform">変換</button>
      </div>
      
      <!-- 
        <label class="form-image-uploader">
        <input id="id_document" type="file" name="file" maxlength="100" class="btn-none" required>画像の選択
      </label>
      <button type="submit" class="btn">
        <div class="img-upload">変換</div>
      </button>
      -->
    </form>
  </div>


  {% if uploaded_file_url %}
<!-- 
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    <p>File uploaded at: <a href="{{ transform_path }}">{{ transform_path }}</a></p>
-->
  <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between">
      <div>
        <img class="preview-origin-image" src="{{ uploaded_file_url }}" alt="">
      </div>
      <div>
        <img class="preview-transform-image" src="{{ transform_path }}" alt="">
      </div>
    </div>
  {% endif %}

</div>




<!-- <img src="static/sample.jpg"> -->
{% endblock %}

django-vue/backend/cnn/templates/upload_img.html
{% extends "./base/_base.html" %} 
{% block content %}

<h2>aaaa</h2>
<h2>画像を登録する</h2>
    <form action="{% url 'cnn:img_upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ upload_form.as_p }}</p>
        <p><input type="submit" value="アップロード"></p>
</form>
{% endblock %}