django-vue/backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from polls import views as polls_views
from cnn import views as cnn_views
from django.conf import settings
from django.conf.urls.static import static
# py ファイルを import することで html で py ファイルが利用可能になる
from polls.dash_apps.finished_apps import testplot, simpleexample, japanese_prefecture, avg_system_man

urlpatterns = [
    # polls ディレクトリと紐付け
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('cnn/', include('cnn.urls')),
    # 理由は分からないが、 django_plotly_dash のパスは必要
    # https://github.com/GibbsConsulting/django-plotly-dash/issues/117
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django-vue/backend/cnn/urls.py
from django.urls import path
from cnn import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = "cnn"
urlpatterns = [
    path('img_upload', views.img_upload, name='img_upload'),
    path('nueral_style', views.nueral_style, name='nueral_style'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-vue/backend/polls/urls.py
from django.urls import path
from . import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = "polls"
urlpatterns = [
    # 引数について説明する
    # 'home'url のパス, views.関数名, name=わかりやすい名前（html 側で {% url 'name'%}を用いてurlを取得可能）
    # ホーム画面
    path('', views.home, name='home'),
    # システムエンジニア（男性）の年収
    path('avg_system_man/', views.avg_system_man, name="dashboard-avg-system-man"),
    # 本サイトについて説明
    path('about', views.about, name='about'),

    ###########################
    ####  demo ################
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # plotly のサンプル
    path('demo/',  views.demo, name='demo'),
    path('demo/japanese_salary/', views.japanese_salary, name='japanese_salary'),
    path('demo/bar/',  views.yearly_avg_co2, name='bar-test'),
    path('demo/demo_japanese_prefecture/', views.demo_japanese_prefecture, name="demo-prefecture"),
    ####  demo ################
    ###########################
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-vue/backend/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.conf import settings

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class CO2(models.Model):
    date = models.DateField()
    average = models.FloatField()

    class Meta:
        ordering = ('date',)

django-vue/backend/polls/forms.py
from django import forms

# html の form で使用
class DateForm(forms.Form):
    start = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

django-vue/backend/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from .models import Question, Choice
from django.template import loader
from django.http import Http404
from django.views.generic import TemplateView 
# import plotly.graph_objects as go
from polls.models import CO2
from django.db.models import Avg
import plotly.express as px
from polls.forms import DateForm
from plotly.offline import plot
import plotly.graph_objects as go

def home(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('home.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def about(request):
    template_name = "about.html"
    return render(request, template_name)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'demo/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'demo/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def demo(request):
    template_name = "demo/demo.html"
    start = request.GET.get('start')
    end = request.GET.get('end')

    co2 = CO2.objects.all()
    if start:
        co2 = co2.filter(date__gte=start)
    if end:
        co2 = co2.filter(date__lte=end)
    print('views.py ---- make px.line')
    fig = px.line(
        x=[c.date for c in co2],
        y=[c.average for c in co2],
        title="CO2 PPM",
        labels={'x': 'Date', 'y': 'CO2 PPM'}
    )


    fig.update_layout(
        title={
            'font_size': 24,
            'xanchor': 'right',
            'x': 0.5
    })

    chart = fig.to_html()
    context = {'chart': chart, 'form': DateForm()}
    return render(request, template_name, context)


def yearly_avg_co2(request):
    template_name = 'demo/demo.html'
    averages = CO2.objects.values('date__year').annotate(avg=Avg('average'))
    x = averages.values_list('date__year', flat=True)
    y = averages.values_list('avg', flat=True)

    fig = px.bar(x=x, y=y)
    fig.update_layout(title_text= 'Average CO2 ')

    chart = fig.to_html()
    context = {'chart': chart, 'form': DateForm()}
    return render(request, template_name, context)



def japanese_salary(request):
    template_name = "demo/japanese_salary.html"
    start = request.GET.get('start')
    end = request.GET.get('end')
    co2 = CO2.objects.all()
    if start:
        co2 = co2.filter(date__gte=start)
    if end:
        co2 = co2.filter(date__lte=end)
    def scatter():
        x1 = [1,2,3,4]
        y1 = [30, 35, 25, 45]

        trace = go.Scatter(
            x=x1,
            y = y1
        )
        layout = dict(
            # title='Simple Graph',
            xaxis=dict(range=[min(x1), max(x1)]),
            yaxis = dict(range=[min(y1), max(y1)]),
        )

        fig = go.Figure(data=[trace], layout=layout)
        plot_div = plot(fig, output_type='div', include_plotlyjs=False)
        return fig, plot_div

    plot1, plot2 =scatter()

    context ={
        'plot1': plot1.to_html(),
        'plot2': plot2,
        'form': DateForm()
    }

    return render(request, template_name, context)


def demo_japanese_prefecture(request):
    template_name = 'demo/japanese_prefecture.html'
    context = {}
    return render(request, template_name, context)

def avg_system_man(request):
    template_name = 'avg_system_man.html'
    context = {}
    return render(request, template_name, context)

django-vue/backend/polls/templates/demo/demo.html
{% extends "../base/_base.html" %} 
{% block content %}
  

  <form method="GET" action="{% url 'polls:demo' %}">
    {{ form.as_p }}
    dashboard_japanese_salary.html
    <button>Submit </button>
  </form>
  
  <div class="graph">{{plot|safe}}</div>
  {{chart | safe}}
  
{% endblock %}

django-vue/backend/polls/templates/demo/detail.html
{% extends "../base/_base.html" %} 
{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }} detail.html</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>
{% endblock %}

django-vue/backend/polls/templates/demo/japanese_prefecture.html
{% extends "../base/_base.html" %} 

  {% block content %}
  {% load plotly_dash %}
  {% plotly_app name="JapanesePrefecture" ratio=1 %}

{% endblock %}

django-vue/backend/polls/templates/demo/japanese_salary.html
{% extends "../base/_base.html" %} 

  {% block content %}
  

  <form method="GET" action="{% url 'polls:japanese_salary' %}">
    {{ form.as_p }}
    <button>Submit </button>
  </form>

  {% load plotly_dash %}
  {% plotly_app name="SimpleExample" ratio=0.4 %}
  {% plotly_app name="testplot" ratio=0.4 %}

{% endblock %}

django-vue/backend/polls/templates/demo/results.html
{% extends "../base/_base.html" %} 
{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}