django-vue/backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from polls import views as polls_views
from cnn import views as cnn_views
from django.conf import settings
from django.conf.urls.static import static
# py ファイルを import することで html で py ファイルが利用可能になる
from polls.dash_apps.finished_apps import testplot, simpleexample, japanese_prefecture, avg_system_man

urlpatterns = [
    # polls ディレクトリと紐付け
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('cnn/', include('cnn.urls')),
    # 理由は分からないが、 django_plotly_dash のパスは必要
    # https://github.com/GibbsConsulting/django-plotly-dash/issues/117
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django-vue/backend/cnn/urls.py
from django.urls import path
from cnn import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = "cnn"
urlpatterns = [
    path('img_upload', views.img_upload, name='img_upload'),
    path('nueral_style', views.nueral_style, name='nueral_style'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-vue/backend/polls/urls.py
from django.urls import path
from . import views
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

app_name = "polls"
urlpatterns = [
    # 引数について説明する
    # 'home'url のパス, views.関数名, name=わかりやすい名前（html 側で {% url 'name'%}を用いてurlを取得可能）
    # ホーム画面
    path('', views.home, name='home'),
    # システムエンジニア（男性）の年収
    path('avg_system_man/', views.avg_system_man, name="dashboard-avg-system-man"),
    # 本サイトについて説明
    path('about', views.about, name='about'),

    ###########################
    ####  demo ################
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # plotly のサンプル
    path('demo/',  views.demo, name='demo'),
    path('demo/japanese_salary/', views.japanese_salary, name='japanese_salary'),
    path('demo/bar/',  views.yearly_avg_co2, name='bar-test'),
    path('demo/demo_japanese_prefecture/', views.demo_japanese_prefecture, name="demo-prefecture"),
    ####  demo ################
    ###########################
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-vue/backend/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.conf import settings

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class CO2(models.Model):
    date = models.DateField()
    average = models.FloatField()

    class Meta:
        ordering = ('date',)

django-vue/backend/polls/forms.py
from django import forms

# html の form で使用
class DateForm(forms.Form):
    start = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

django-vue/backend/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from .models import Question, Choice
from django.template import loader
from django.http import Http404
from django.views.generic import TemplateView 
# import plotly.graph_objects as go
from polls.models import CO2
from django.db.models import Avg
import plotly.express as px
from polls.forms import DateForm
from plotly.offline import plot
import plotly.graph_objects as go

def home(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('home.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def about(request):
    template_name = "about.html"
    return render(request, template_name)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'demo/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'demo/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def demo(request):
    template_name = "demo/demo.html"
    start = request.GET.get('start')
    end = request.GET.get('end')

    co2 = CO2.objects.all()
    if start:
        co2 = co2.filter(date__gte=start)
    if end:
        co2 = co2.filter(date__lte=end)
    print('views.py ---- make px.line')
    fig = px.line(
        x=[c.date for c in co2],
        y=[c.average for c in co2],
        title="CO2 PPM",
        labels={'x': 'Date', 'y': 'CO2 PPM'}
    )


    fig.update_layout(
        title={
            'font_size': 24,
            'xanchor': 'right',
            'x': 0.5
    })

    chart = fig.to_html()
    context = {'chart': chart, 'form': DateForm()}
    return render(request, template_name, context)


def yearly_avg_co2(request):
    template_name = 'demo/demo.html'
    averages = CO2.objects.values('date__year').annotate(avg=Avg('average'))
    x = averages.values_list('date__year', flat=True)
    y = averages.values_list('avg', flat=True)

    fig = px.bar(x=x, y=y)
    fig.update_layout(title_text= 'Average CO2 ')

    chart = fig.to_html()
    context = {'chart': chart, 'form': DateForm()}
    return render(request, template_name, context)



def japanese_salary(request):
    template_name = "demo/japanese_salary.html"
    start = request.GET.get('start')
    end = request.GET.get('end')
    co2 = CO2.objects.all()
    if start:
        co2 = co2.filter(date__gte=start)
    if end:
        co2 = co2.filter(date__lte=end)
    def scatter():
        x1 = [1,2,3,4]
        y1 = [30, 35, 25, 45]

        trace = go.Scatter(
            x=x1,
            y = y1
        )
        layout = dict(
            # title='Simple Graph',
            xaxis=dict(range=[min(x1), max(x1)]),
            yaxis = dict(range=[min(y1), max(y1)]),
        )

        fig = go.Figure(data=[trace], layout=layout)
        plot_div = plot(fig, output_type='div', include_plotlyjs=False)
        return fig, plot_div

    plot1, plot2 =scatter()

    context ={
        'plot1': plot1.to_html(),
        'plot2': plot2,
        'form': DateForm()
    }

    return render(request, template_name, context)


def demo_japanese_prefecture(request):
    template_name = 'demo/japanese_prefecture.html'
    context = {}
    return render(request, template_name, context)

def avg_system_man(request):
    template_name = 'avg_system_man.html'
    context = {}
    return render(request, template_name, context)

django-vue/backend/polls/templates/about.html
{% extends "./base/_base.html" %} 
{% block content %}


<div class="py-5">
  <div class="container">
    <div class="row-cols-10 row-cols-sm-10 row-cols-md-10 g-3">
        <div class="d-grid gap-3 bg-light">
          <p class="p-2 fs-3">本サイトについて</p>
          <p class="p-2">
            学習のアウトプットとして開発したダッシュボードやツールを公開します。<br>
            Webフレームワーク:Django<br>
            方針：ダッシュボードや画像認識、組み込みに関するツールを本サイトに実装していきます。<br>
          </p>

          <p class="p-2 fs-3">作成予定</p>
          <p class="p-2">・オートエンコーダーを用いた画像変換ツール。機能の例）ゴッホのタッチに画像を加工など。</p>

          <p class="p-2 fs-3">コード</p>
          <p class="p-2">・<a href="https://github.com/Kunihiro-ikd" target="_blank">github</a> </p>
      </div>
    </div>
</div>
{% endblock %}

django-vue/backend/polls/templates/avg_system_man.html
{% extends "./base/_base.html" %} 
{% block content %}

  {% load plotly_dash %}
  {% plotly_app name="AvgSystemMan" ratio=1 %}

{% endblock %}

django-vue/backend/polls/templates/dashboard_japanese_salary.html
<!doctype html>
<html lang="ja">
<head>
      {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <!-- <img src="{% static 'assets/img/sample.jpg' %}" class="test-panda"> -->
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'static_app/css/style.css' %}">
    <title>output</title>
</head>
<body>

  <!-- ヘッダー -->
  <header class="p-3 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between">
          <div class="h4">output</div>
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
  
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
              <li><a href="#" class="nav-link px-2 text-white">About（工事中）</a></li>
            </ul>
    
          </div>
        </div>
      </div>
    </header>
  <!-- ヘッダー -->
  
  <h2>dashboard japanese dashboard</h2>

  {% block content %}
  <div class="title"><h1>Plotlyのグラフを描画</h1></div>
  <div class="graph">{{plot|safe}}</div>
  
  {{chart | safe}}
  
  {% endblock %}
</body>

django-vue/backend/polls/templates/home.html
{% extends "./base/_base.html" %} 
{% block content %}
<div class="album py-5">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <!-- one block  -->
      <div class="col">
        <div class="card shadow-sm">
          <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> -->
          <img src="static/images/japan_salary.jpg" style="overflow-y: hidden;" alt="" height="225">
          
          <div class="card-body">
            <p class="card-text">
              <a href={% url 'polls:dashboard-avg-system-man' %} class="nav-link px-2 text-secondary"> 【ダッシュボード】　都道府県別システムエンジニア（男性）の平均年収</a>
            </p>
            <p class="card-text"></p>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted">plotly, dash, pandas</small>
            </div>
          </div>
        </div>
      </div>
      <!-- one block  -->
      <!-- one block  -->
      <div class="col">
      <div class="card shadow-sm">
        <img src="static/images/img_generator.png" alt="" width="100%" max-height="225">
        

        <div class="card-body">
          <p class="card-text">
            <a href={% url 'cnn:nueral_style' %} class="nav-link px-2 text-secondary">【CNN】画像変換ツールの作成。機能の例）ゴッホのタッチに画像を加工し画面に表示など</a> 
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted">dashboard</small>
          </div>
        </div>
      </div>
    </div>
    <!-- one block  -->
    </div>
  </div>
</div>

{% endblock %}